package com.wg.domain;

import java.util.Date;

public class VipMemberInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_member_info.mobile
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_member_info.vip_name
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    private String vipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_member_info.vip_sex
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    private String vipSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_member_info.address
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_member_info.gmt_create
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    private Date gmtCreate;

    private String gmtCreateStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_member_info.gmt_modity
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    private Date gmtModity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_member_info.remark
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_member_info.status
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_member_info.level
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_member_info.mobile
     *
     * @return the value of vip_member_info.mobile
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_member_info.mobile
     *
     * @param mobile the value for vip_member_info.mobile
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_member_info.vip_name
     *
     * @return the value of vip_member_info.vip_name
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public String getVipName() {
        return vipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_member_info.vip_name
     *
     * @param vipName the value for vip_member_info.vip_name
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public void setVipName(String vipName) {
        this.vipName = vipName == null ? null : vipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_member_info.vip_sex
     *
     * @return the value of vip_member_info.vip_sex
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public String getVipSex() {
        return vipSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_member_info.vip_sex
     *
     * @param vipSex the value for vip_member_info.vip_sex
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public void setVipSex(String vipSex) {
        this.vipSex = vipSex == null ? null : vipSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_member_info.address
     *
     * @return the value of vip_member_info.address
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_member_info.address
     *
     * @param address the value for vip_member_info.address
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_member_info.gmt_create
     *
     * @return the value of vip_member_info.gmt_create
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_member_info.gmt_create
     *
     * @param gmtCreate the value for vip_member_info.gmt_create
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_member_info.gmt_modity
     *
     * @return the value of vip_member_info.gmt_modity
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public Date getGmtModity() {
        return gmtModity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_member_info.gmt_modity
     *
     * @param gmtModity the value for vip_member_info.gmt_modity
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public void setGmtModity(Date gmtModity) {
        this.gmtModity = gmtModity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_member_info.remark
     *
     * @return the value of vip_member_info.remark
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_member_info.remark
     *
     * @param remark the value for vip_member_info.remark
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_member_info.status
     *
     * @return the value of vip_member_info.status
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_member_info.status
     *
     * @param status the value for vip_member_info.status
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_member_info.level
     *
     * @return the value of vip_member_info.level
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_member_info.level
     *
     * @param level the value for vip_member_info.level
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    public String getGmtCreateStr() {
        return gmtCreateStr;
    }

    public void setGmtCreateStr(String gmtCreateStr) {
        this.gmtCreateStr = gmtCreateStr;
    }

    @Override
    public String toString() {
        return "VipMemberInfo{" +
                "mobile='" + mobile + '\'' +
                ", vipName='" + vipName + '\'' +
                ", vipSex='" + vipSex + '\'' +
                ", address='" + address + '\'' +
                ", gmtCreate=" + gmtCreate +
                ", gmtCreateStr='" + gmtCreateStr + '\'' +
                ", gmtModity=" + gmtModity +
                ", remark='" + remark + '\'' +
                ", status='" + status + '\'' +
                ", level='" + level + '\'' +
                '}';
    }
}