package com.wg.dao;

import java.util.List;

import com.wg.domain.ContactInfo;
import com.wg.domain.ContactInfoExample;
import org.apache.ibatis.annotations.Param;

public interface ContactInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_info
     *
     * @mbggenerated Sun Oct 15 18:57:20 CST 2017
     */
    int countByExample(ContactInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_info
     *
     * @mbggenerated Sun Oct 15 18:57:20 CST 2017
     */
    int deleteByExample(ContactInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_info
     *
     * @mbggenerated Sun Oct 15 18:57:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_info
     *
     * @mbggenerated Sun Oct 15 18:57:20 CST 2017
     */
    int insert(ContactInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_info
     *
     * @mbggenerated Sun Oct 15 18:57:20 CST 2017
     */
    int insertSelective(ContactInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_info
     *
     * @mbggenerated Sun Oct 15 18:57:20 CST 2017
     */
    List<ContactInfo> selectByExample(ContactInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_info
     *
     * @mbggenerated Sun Oct 15 18:57:20 CST 2017
     */
    ContactInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_info
     *
     * @mbggenerated Sun Oct 15 18:57:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") ContactInfo record, @Param("example") ContactInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_info
     *
     * @mbggenerated Sun Oct 15 18:57:20 CST 2017
     */
    int updateByExample(@Param("record") ContactInfo record, @Param("example") ContactInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_info
     *
     * @mbggenerated Sun Oct 15 18:57:20 CST 2017
     */
    int updateByPrimaryKeySelective(ContactInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_info
     *
     * @mbggenerated Sun Oct 15 18:57:20 CST 2017
     */
    int updateByPrimaryKey(ContactInfo record);
}