package com.wg.dao;


import java.util.List;

import com.wg.domain.VipMemberInfo;
import com.wg.domain.VipMemberInfoExample;
import org.apache.ibatis.annotations.Param;

public interface VipMemberInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_member_info
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    int countByExample(VipMemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_member_info
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    int deleteByExample(VipMemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_member_info
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    int deleteByPrimaryKey(String mobile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_member_info
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    int insert(VipMemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_member_info
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    int insertSelective(VipMemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_member_info
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    List<VipMemberInfo> selectByExample(VipMemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_member_info
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    VipMemberInfo selectByPrimaryKey(String mobile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_member_info
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") VipMemberInfo record, @Param("example") VipMemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_member_info
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    int updateByExample(@Param("record") VipMemberInfo record, @Param("example") VipMemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_member_info
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    int updateByPrimaryKeySelective(VipMemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_member_info
     *
     * @mbggenerated Sun Oct 15 14:03:11 CST 2017
     */
    int updateByPrimaryKey(VipMemberInfo record);
}